spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_vendor?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Akshay@1996

  jpa:
    hibernate:
      ddl-auto: create
